[tools]
claude = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-x64/claude"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/stable" }
codex = "latest"
gcloud = "latest"
gh = "latest"
"github:Kong/deck" = "1.54.0"
"github:agavra/tuicr" = "latest"
"github:always-further/nono" = "latest"
"github:chmouel/lazyworktree" = "latest"
"github:kong/kongctl" = "v0.7.0"
"github:speakeasy-api/speakeasy" = "1.700.1"
go = "latest"
gofumpt = "latest"
golangci-lint = "2.11.4"
jq = "latest"
kubectl = "latest"
mockery = "latest"
neovim = "0.12.1"
node = "25.1.0"
"npm:@openchamber/web" = "latest"
opencode = "latest"
python = "3.11"
starship = "1.24.2"
terraform = "latest"
tmux = "3.6a"
vale = "latest"
vercel = "latest"
yq = "latest"
